### ISSUE TITLE
Scan taking a full 20 seconds on Kobo Aura

### ISSUE THREAD

**Issue by projectgus** [koreader/lj-wpaclient#12]
I was emboldened to try and figure out why my Kobo Aura always shows "Scanning for networks..." for a full 20 seconds each time it connects to Wi-Fi...

Uncommenting the print statements in `wpaclient.lua` (and adding two of my own log lines in koreader to confirm timing), I see:

```
10/10/24-21:38:37 DEBUG WpaSupplicant:getNetworkList scanning 
SCAN reply:     OK
3       1       1       0       CTRL-EVENT-BSS-ADDED 0 14:d8:64:xx:xx:xx
4       1       1       0       CTRL-EVENT-BSS-ADDED 1 d4:6e:0e:xx:xx:xx
5       1       1       1       CTRL-EVENT-SCAN-RESULTS
5       2       1       1       CTRL-EVENT-NETWORK-NOT-FOUND
10/10/24-21:38:57 DEBUG WpaSupplicant:getNetworkList scan done 
```

It seems like in the case of the Aura, this comment is wrong:

```
            -- If we get CTRL-EVENT-NETWORK-NOT-FOUND, it means no preferred networks were found during the scan.
            -- It also means *another* scan will be fired, so this invalidates CTRL-EVENT-SCAN-RESULTS,
            -- as the actual CTRL-EVENT-SCAN-STARTED may be delayed until our next iteration...
            -- It may take *multiple* scans, and events may be split across multiple reads...
            -- Which is why NetworkManager does another pass of waiting in case our heuristics fail...
            elseif ev.msg == "CTRL-EVENT-NETWORK-NOT-FOUND" then
                found_result = false
                expected_scans = expected_scans + 1
```

On the Aura, seems wpa_supplicant sends `CTRL-EVENT-NETWORK-NOT-FOUND` but doesn't start any new scan.

I note that the Aura is also one of the "older devices" that doesn't send `CTRL-EVENT-SCAN-STARTED`. (yay for ancient wpa_supplicant versions?)

Do you think it'd be reasonable to add a "quirk" here of "if wpa_supplicant didn't send `CTRL-EVENT-SCAN-STARTED` or "FAIL-BUSY*" as the first reply then assume it's old and cursed, so ignore `CTRL-EVENT-NETWORK-NOT-FOUND`?"

I'd be very happy to try and put something together and send a PR, but I don't have any devices to test with apart from two Auras...

**Comment by projectgus** [comment]
>  no preferred networks were found during the scan

Poking around a bit more, I realised that `wcli:listNetworks())` is empty when the `CTRL-EVENT-NETWORK-NOT-FOUND` event comes back.

So maybe better logic could be to call `listNetworks()` before scanning, and ignore `CTRL-EVENT-NETWORK-NOT-FOUND` if there are no networks configured at all? I don't know if that's a behaviour that's different on later wpa_supplicant or not?

(Again, happy to put together a PR if any of these sound like reasonable ideas to you.)

**Comment by Frenzie** [comment]
That code was only changed recently btw: https://github.com/koreader/lj-wpaclient/pull/11

It's not strictly impossible that it worked fine/better with older devices; I have no idea really.

**Comment by NiLuJe** [comment]
> "if wpa_supplicant didn't send `CTRL-EVENT-SCAN-STARTED` or "FAIL-BUSY*"

That would penalize other old devices that don't support the SCAN-STARTED event, but *do* trip a rescan on their own (e.g., the H2O behaves this way, IIRC).

The least terrible option I can think of might simply be to flag certain devices as broken and stop them from incrementing `expected_scans`on `CTRL-EVENT-NETWORK-NOT-FOUND`...

(I don't remember how it's all tied together right now, but basically set a WpaClient flag from within Device in front, and do `expected_scans = expected_scans + self.automatic_rescan and 1 or 0` instead of the current `+1`).

Especially since I'd be wary of making the heuristics even more brittle ;).

**Comment by projectgus** [comment]
Thanks @Frenzie and @NiLuJe for the context and pointers.

 > IIRC, `LIST_NETWORKS` should only be empty if _nothing_ ever saved a preferred network. And by nothing, I mean Nickel, as I'm not even sure ours would ever end up in there, as we don't store them via wpa_supplicant IIRC. And since 95% of people will have setup their device via Wi-Fi (and that number is unlikely to go lower, since they're killing Nickel desktop, last I heard?), that's an unlikely scenario ;).

Ah... I hadn't realised that Nickel writes to wpa_supplicant.conf. I had removed my network settings from Nickel on the reasoning of "I don't ever use Nickel, and Koreader can manage Wi-Fi for me". If I add the Wi-Fi network back in Nickel then the delay goes away and it connects in a couple of seconds. :magic_wand:  :grinning: 

If none of the preferred networks are found by the scan then I still get the 20 second "Scanning for networks..." prompt before the scan results pop up. The log shows variations on:

```
10/11/24-07:53:26 DEBUG WpaSupplicant:getNetworkList scanning 
SCAN reply:     OK
3       1       1       0       CTRL-EVENT-BSS-ADDED 0 e8:31:cd:xx:xx:xx
3       1       1       1       CTRL-EVENT-SCAN-RESULTS
3       2       1       1       CTRL-EVENT-NETWORK-NOT-FOUND
34      2       1       2       CTRL-EVENT-SCAN-RESULTS
34      3       1       2       CTRL-EVENT-NETWORK-NOT-FOUND
58      3       1       3       CTRL-EVENT-SCAN-RESULTS
58      4       1       3       CTRL-EVENT-NETWORK-NOT-FOUND
10/11/24-07:53:46 DEBUG WpaSupplicant:getNetworkList scan done 
10/11/24-07:53:46 DEBUG WpaSupplicant:getCurrentNetwork: Connected network: SCANNING 
10/11/24-07:53:46 DEBUG WpaSupplicant:getCurrentNetwork: Current network: nil 
```

Which seems more like expected behaviour with wpa_supplicant still scanning in the background, yes?

So I guess I should close this?

FWIW I would still be happy to submit a PR that ends the scan earlier if there are no "preferred" networks in `wpa_supplicant`[1], but if we're expected to configure networks in Nickel (or the equivalent) rather than Koreader then the current behaviour also makes sense to me now.

[1] The "correct" way to do this might be to watch for `wpa_state=INACTIVE` rather than `SCANNING`, but I haven't confirmed this is what my Kobo's wpa_supplicant does each time if there's nothing configured.

**Comment by NiLuJe** [comment]
> Which seems more like expected behaviour with wpa_supplicant still scanning in the background, yes?

Looks like it, yeah ;).

> I would still be happy to submit a PR that ends the scan earlier if there are no "preferred" networks in wpa_supplicant

That sounds like a good idea, yeah. Like you might have surmised from my earlier comments, that's a scenario I 100% did not even test ;p.

**Comment by NiLuJe** [comment]
> wpa_state=INACTIVE

I don't rightly recall either, but if it tracks, that is indeed much more elegant ;).

**Comment by projectgus** [comment]
Sounds great, have submitted a PR along those lines in #13.

This also got me thinking some more: I know some folks have multiple APs with different signal strengths and stuff like this, but I have exactly one Wi-Fi network configured in Koreader - my single home router.

So if I'm opening Koreader at home, it usually connects in a couple of seconds. If I'm opening it outside my house, it will never find a configured network and I'll just sit there for 20 seconds watching it "Scanning..." before I can start reading.

Therefore I was wondering, would you consider a adding a "Maximum scan time" option? In seconds, default value 20 and allowed range maybe 3 to 30? I'd be happy to submit PRs for this if it was something you'd consider adding. Totally understand if it's option-itis, though.

**Comment by NiLuJe** [comment]
> Totally understand if it's option-itis, though.

Kinda feels like that ;).

My home AP routinely takes more than 15s to be caught in a busy apartment complex on some devices, for instance. And, I'm, like, 5m away from it ;).

**Comment by NiLuJe** [comment]
> If I'm opening it outside my house, it will never find a configured network and I'll just sit there for 20 seconds watching it "Scanning..." before I can start reading.

Out of curiosity, and in the spirit of https://github.com/koreader/lj-wpaclient/pull/13#issuecomment-2408651058, which state is wpa_supplicant reporting in this case?

**Comment by projectgus** [comment]
> My home AP routinely takes more than 15s to be caught in a busy apartment complex on some devices, for instance. And, I'm, like, 5m away from it ;).

Right, I see. We're roughly opposites, as I live in a country area where there are usually two 2.4GHz APs in range and I'm responsible for both of them. :)

> > If I'm opening it outside my house, it will never find a configured network and I'll just sit there for 20 seconds watching it "Scanning..." before I can start reading.
> 
> Out of curiosity, and in the spirit of https://github.com/koreader/lj-wpaclient/pull/13#issuecomment-2408651058, which state is wpa_supplicant reporting in this case?

It reports `SCANNING` all the way through. (Unless no networks are configured in wpa_supplicant, in which case it does one round of scanning and then goes `INACTIVE`).

Out of curiosity I tried patching `iter <80` to `iter < 240` (i.e. scan for up to 60 seconds) without any known APs visible and it still reports `SCANNING` at the end.

---

I understand if you don't want to cram in too many more heuristics, but a useful one for my "country" use case might be "return early after seeing `CTRL-EVENT-NETWORK-NOT-FOUND` twice in a row with no new scan results found in between." I'm guessing that probably doesn't happen in the apartment case. :)

**Comment by projectgus** [comment]
> Except it looks like you _do_ get `CTRL-EVENT-SCAN-RESULTS` interleaved w/ `CTRL-EVENT-NETWORK-NOT-FOUND` (according to your excerpt in [#12 (comment)](https://github.com/koreader/lj-wpaclient/issues/12#issuecomment-2406109893)).
> 
> (Unless you meant actually parsing the result lists, e.g., `getScanResults`? (In which case, I'm even _less_ enthused about that approach ;p).

Something like this (I haven't tested this, just to give the idea):

```patch
diff --git i/wpaclient.lua w/wpaclient.lua
index 833b9d3..207c197 100644
--- i/wpaclient.lua
+++ w/wpaclient.lua
@@ -177,6 +177,7 @@ function WpaClient.__index:scanThenGetResults()
     local started_scans = 0
     local finished_scans = 0
     local expected_scans = 1
+    local empty_result = false
     local iter = 0
     while not done and iter < 80 do
         iter = iter + 1
@@ -223,6 +224,13 @@ function WpaClient.__index:scanThenGetResults()
                 found_result = false
                 expected_scans = expected_scans + 1
 
+                if empty_result then
+                    -- We've gotten from one CTRL-EVENT-NETWORK-NOT-FOUND event to the next
+                    -- without anything else reported, so stop scanning
+                    done = true
+                end
+                empty_result = true
+
             -- Wait for every started scan to finish
             -- NOTE: Because everything is terrible, this event isn't sent on older devices... -_-"
             elseif ev.msg == "CTRL-EVENT-SCAN-STARTED" then
@@ -234,6 +242,10 @@ function WpaClient.__index:scanThenGetResults()
             -- Do break on successful connection, though ;).
             elseif string.sub(ev.msg, 1, 20) == "CTRL-EVENT-CONNECTED" then
                 found_result = true
+
+            -- Another event from wpa_supplicant, probably either a new network or a connection
+            else
+                empty_result = false
             end
 
             -- For debugging purposes
```

but it's OK, I can see why you wouldn't want this extra complexity in there so I'll stop suggesting random behaviour changes after this one. :grin: .

**Comment by NiLuJe** [comment]
I mean, if you can come up with something not too gnarly/invasive that actually works, I'm not necessarily against it ;).
